# Generated by Django 4.2 on 2023-04-08 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("completed", models.BooleanField(default=False)),
                ("order_id", models.PositiveIntegerField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todo_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        # since django orm constraints doesn't work on database level, and ruins the usage of bulk views
        # I decided to use raw sql to create a unique constraint on the user_id and order_id
        # https://github.com/miki725/django-rest-framework-bulk/issues/57
        migrations.RunSQL(
            "CREATE UNIQUE INDEX unique_order ON core_todoitem(user_id, order_id);",
        ),
    ]
